[tool.poetry]
name = "new-homework"
version = "0.1.0"
description = ""
authors = ["AlexeyVedenkin <alexey.vedenkin@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
